#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="$ROOT_DIR/docs/wiki"
OUT_FILE="$OUT_DIR/code-map.md"

mkdir -p "$OUT_DIR"

count_files() {
  find "$ROOT_DIR/mac-app" "$ROOT_DIR/tests" "$ROOT_DIR/scripts" -type f \( -name '*.swift' -o -name '*.js' -o -name '*.sh' \) | wc -l | tr -d ' '
}

total_lines() {
  find "$ROOT_DIR/mac-app" "$ROOT_DIR/tests" "$ROOT_DIR/scripts" -type f \( -name '*.swift' -o -name '*.js' -o -name '*.sh' \) -print0 \
    | xargs -0 wc -l \
    | tail -n 1 \
    | awk '{print $1}'
}

swift_lines() {
  find "$ROOT_DIR/mac-app" -name '*.swift' -print0 \
    | xargs -0 wc -l \
    | tail -n 1 \
    | awk '{print $1}'
}

write_largest_files() {
  find "$ROOT_DIR/mac-app" "$ROOT_DIR/tests" "$ROOT_DIR/scripts" -type f \( -name '*.swift' -o -name '*.js' -o -name '*.sh' \) -print0 \
    | xargs -0 wc -l \
    | sort -nr \
    | head -n 30 \
    | awk -v root="$ROOT_DIR/" '{
        if ($2 == "total") next;
        path=$2;
        sub(root, "", path);
        printf "| `%s` | %s |\n", path, $1
      }'
}

write_matching_files() {
  local title="$1"
  local pattern="$2"
  echo "## $title"
  echo
  find "$ROOT_DIR/mac-app" -maxdepth 1 -name "$pattern" -print \
    | sed "s#$ROOT_DIR/##" \
    | sort \
    | awk '{ printf "- `%s`\n", $0 }'
  echo
}

write_swift_types() {
  rg -n "^(final class|class|struct|enum|protocol|extension) " "$ROOT_DIR/mac-app" \
    | sed "s#$ROOT_DIR/##" \
    | awk -F: '{ printf "| `%s` | %s | `%s` |\n", $1, $2, $3 }'
}

cat > "$OUT_FILE" <<EOF
# Code Map

Generated by \`./scripts/generate_code_wiki.sh\`.

## Summary

- Code files: $(count_files)
- Main code lines: $(total_lines)
- Swift app lines: $(swift_lines)

## Largest Files

| File | Lines |
| --- | ---: |
$(write_largest_files)

$(write_matching_files "Reader Window Modules" "ReaderWindowController*.swift")
$(write_matching_files "AI Chat Modules" "AIChatPanel*.swift")
$(write_matching_files "Document Loading Modules" "DocumentLoading*.swift")
$(write_matching_files "Recent Documents Modules" "RecentDocuments*.swift")

## Swift Type Index

| File | Line | Declaration |
| --- | ---: | --- |
$(write_swift_types)
EOF

echo "Generated $OUT_FILE"
